Adicionando guia de contribuição #13
fga-eps-mds/2023-1-Dnit-DOC pull request #15
Opened 2023-05-12 14:15 UTC by yandrade1305

2023-05-12 15:45 UTC, Fealps requested changes
Favor adicionar versionamento, e tipo de licença do projeto.
Além disso ajuste o commit de exemplo p conter o numero da issue na frente do commit.

Em politicas de issues não vai constar o Hotfix ou WIP?
Sugiro tbm uma politica para nomear as branch contendo subpasta
exemplo:
tipo/x-nome-da-issue
onde tipo pode ser doc, feature, refactor etc.
acha q é valido?

2023-05-12 16:43 UTC, DenysRogeres commented on docs/docs/GuiaDeContribuicao/guiaDeContribuicao.md
> +### **NOVAS BRANCHES**
Este documento já tem a política de issues e política de commits, esta parte seria a política de branchs? Se for o caso, ainda não ficou claro como serão tratados as branchs, caso não seja essa parte, pq esse documento não está aqui também?

2023-05-12 16:44 UTC, DenysRogeres reviewed
Rever tópico de política de branchs pois deve fazer parte do documento

2023-05-15 13:32 UTC, Fealps approved these changes

2023-05-15 13:32 UTC, merged